icarus-consulting/Xive

src/Xive/Cell/FileCell.cs
src/Xive/Comb/FileComb.cs
src/Xive/Comb/RamComb.cs
tests/Test.Xive/Comb/FileCombTests.cs
tests/Test.Xive/Comb/RamCombTests.cs

#2 
closes #2 
fix: fixes RamCell name in RamCom

Implement guts in cells

---

Xive.sln
src/Xive/Cell/CachedCell.cs
src/Xive/Cell/FileCell.cs
src/Xive/Comb/FileComb.cs
src/Xive/Xocument/CellXocument.cs
tests/Test.Xive/Cell/CachedCellTests.cs
tests/Test.Xive/Comb/FileCombTests.cs
tests/Test.Xive/Comb/RamCombTests.cs

I5 update cached flip

---

README.md
src/Xive/Hive/CachedHive.cs
src/Xive/Hive/MutexHive.cs
tests/Test.Xive/Hive/CachedHiveTests.cs
tests/Test.Xive/Hive/MutexHiveTest.cs

closes #11 
closes #10 
closes #9

I11 confusing ctors

---

src/Xive/Comb/CachedComb.cs
src/Xive/Hive/CachedHive.cs
src/Xive/Xocument/CachedXocument.cs
tests/Test.Xive/Comb/CachedCombTests.cs

refactor: allow cache size definition and simplify code

---

src/Xive/Cell/CachedCell.cs
src/Xive/Cell/MutexCell.cs
src/Xive/Comb/MutexComb.cs
src/Xive/Xocument/CellXocument.cs
src/Xive/Xocument/MutexXocument.cs
tests/Test.Xive/Cell/MutexCellTest.cs
tests/Test.Xive/Comb/MutexCombTests.cs
tests/Test.Xive/Hive/MutexHiveTest.cs
tests/Test.Xive/ParallelFunc.cs

I16 mutex broken

---

src/Xive/Cell/CachedCell.cs
src/Xive/Cell/FileCell.cs
src/Xive/Cell/MutexCell.cs
src/Xive/Cell/RamCell.cs
src/Xive/Cell/SyncCell.cs
src/Xive/Comb/CachedComb.cs
src/Xive/Comb/MutexComb.cs
src/Xive/Hive/SimpleHive.cs
src/Xive/ICell.cs
src/Xive/StrictCellName.cs
src/Xive/StrictCoordinate.cs
src/Xive/Xocument/CellXocument.cs
src/Xive/Xocument/MutexXocument.cs
tests/Test.Xive/Cell/FileCellTests.cs
tests/Test.Xive/Cell/MutexCellTest.cs
tests/Test.Xive/Comb/FileCombTests.cs
tests/Test.Xive/Comb/MutexCombTests.cs
tests/Test.Xive/FkCell.cs
tests/Test.Xive/Hive/FileHiveTests.cs
tests/Test.Xive/ParallelFunc.cs
tests/Test.Xive/Test.Xive.csproj
tests/Test.Xive/VerboseCell.cs
tests/Test.Xive/Xocument/MutexXocumentTests.cs

I18 threadsafeness

---

src/Xive/Cell/CachedCell.cs
src/Xive/Cell/RamCell.cs
src/Xive/Comb/CachedComb.cs
src/Xive/Xocument/CachedXocument.cs
tests/Test.Xive/Cell/CachedCellTests.cs
tests/Test.Xive/Cell/FileCellTests.cs
tests/Test.Xive/Cell/RamCellTests.cs
tests/Test.Xive/Hive/CachedHiveTests.cs
tests/Test.Xive/Xocument/CachedXocumentTests.cs

I27 prevent type switching

---

src/Xive/Hive/FileHive.cs
src/Xive/Hive/RamHive.cs
tests/Test.Xive/Hive/CachedHiveTests.cs
tests/Test.Xive/Hive/FileHiveTests.cs
tests/Test.Xive/Hive/RamHiveTests.cs

fix: shifting overrides cells/xocuments in cached filehive

---

src/Xive/Xocument/CellXocument.cs
tests/Test.Xive/Xocument/CellXocumentTests.cs

xDocument has encoding and save header files

---

src/Xive/Xive.csproj
src/Xive/Xocument/CellXocument.cs
src/Xive/Xocument/Xambly/AddIfAttributeDirective.cs
tests/Test.Xive/Cell/FileCellTests.cs
tests/Test.Xive/Test.Xive.csproj
tests/Test.Xive/Xocument/CellXocumentTests.cs

Use UTF16 when writing XML

---

src/Xive/Cell/FileCell.cs
src/Xive/Cell/RamCell.cs
src/Xive/Cell/SyncCell.cs
src/Xive/Comb/FileComb.cs
src/Xive/Comb/RamComb.cs
src/Xive/StrictCoordinate.cs
src/Xive/Xive.csproj
src/Xive/Xocument/CellXocument.cs
src/Xive/Xocument/SimpleXocument.cs
src/Xive/Xocument/Xambly/AddIfAttributeDirective.cs
tests/Test.Xive/Cell/CachedCellTests.cs
tests/Test.Xive/Test.Xive.csproj
tests/Test.Xive/Xocument/CachedXocumentTests.cs

refactor: adopt Atoms 0.26.0

---

README.md

#38 
The build badge has the correct repo url
closes #38

docs: correct repo url in build badge

---

src/Xive/Cell/CachedCell.cs
src/Xive/Comb/CachedComb.cs
src/Xive/Hive/CachedHive.cs
src/Xive/Hive/SimpleHive.cs
src/Xive/Xocument/CachedXocument.cs
tests/Test.Xive/Cell/CachedCellTests.cs
tests/Test.Xive/Comb/CachedCombTests.cs
tests/Test.Xive/Hive/CachedHiveTests.cs
tests/Test.Xive/Xocument/CachedXocumentTests.cs

feat: enable CachedXive to blacklist items

---

src/Xive/Hive/CachedHive.cs
tests/Test.Xive/Hive/CachedHiveTests.cs

maxBytes are always considered

---

src/Xive/Hive/CachedHive.cs
tests/Test.Xive/Hive/CachedHiveTests.cs

fix: CachedHive shifted passes blacklist

---

src/Xive/Cache/BlacklistCache.cs
src/Xive/Cache/ICache.cs
src/Xive/Cache/LimitedCache.cs
src/Xive/Cache/SimpleCache.cs
src/Xive/Cell/CachedCell.cs
src/Xive/Cell/MutexCell.cs
src/Xive/Comb/CachedComb.cs
src/Xive/Comb/FileComb.cs
src/Xive/Hive/CachedHive.cs
src/Xive/Hive/MutexHive.cs
src/Xive/Xive.csproj
src/Xive/Xocument/CachedXocument.cs
src/Xive/Xocument/MutexXocument.cs
tests/Test.Xive/Cache/BlacklistCacheTests.cs
tests/Test.Xive/Cache/LimitedCacheTests.cs
tests/Test.Xive/Cache/SimpleCacheTests.cs
tests/Test.Xive/Cell/CachedCellTests.cs
tests/Test.Xive/Comb/CachedCombTests.cs
tests/Test.Xive/Hive/CachedHiveTests.cs
tests/Test.Xive/Test.Xive.csproj
tests/Test.Xive/Xocument/CachedXocumentTests.cs

closes #55 
closes #54 
closes #53 
closes #52 
closes #51 
CachedHive is setup using a ICache object now.

Multiple Improvements

---

src/Xive/Xocument/CellXocument.cs
tests/Test.Xive/Xocument/CellXocumentTests.cs

closes #58 
CellXocument delivers meaningful exception when XML is invalid.

Meaningful exception message on invalid XML content

---

src/Xive/Xocument/MutexXocument.cs
tests/Test.Xive/Hive/CatalogTests.cs

Fix: Accessing catalog multithreaded fails

---

src/Xive/Cache/BlacklistCache.cs
src/Xive/Cache/ICache.cs
src/Xive/Cache/LimitedCache.cs
src/Xive/Cache/SimpleCache.cs
src/Xive/Cell/CachedCell.cs
src/Xive/Xocument/CachedXocument.cs
tests/Test.Xive/Cache/BlacklistCacheTests.cs
tests/Test.Xive/Cache/LimitedCacheTests.cs
tests/Test.Xive/Cache/SimpleCacheTests.cs
tests/Test.Xive/Hive/CatalogTests.cs

I64 cached hive does not work parallel

---

src/Xive/Hive/MutexHive.cs
src/Xive/Xocument/MutexXocument.cs

fix: mutexHive does not block the hive anymore

---

src/Xive/Cache/SimpleCache.cs
tests/Test.Xive/Cache/SimpleCacheTests.cs

fix: cache is insensitive to separator chars now

---

src/Xive/Cell/RamCell.cs
tests/Test.Xive/Cell/RamCellTests.cs
tests/Test.Xive/Hive/RamHiveTests.cs

fix: ramcell is separator insensitive now

---

src/Xive/Cache/SimpleCache.cs
src/Xive/Cell/RamCell.cs
src/Xive/Comb/RamComb.cs
src/Xive/Normalized.cs
tests/Test.Xive/Cache/SimpleCacheTests.cs
tests/Test.Xive/Cell/RamCellTests.cs
tests/Test.Xive/Comb/RamCombTests.cs
tests/Test.Xive/Hive/RamHiveTests.cs

I72 add case insensitiveness

---

src/Xive/Cache/SimpleCache.cs
src/Xive/Cell/CachedCell.cs
src/Xive/Cell/FileCell.cs
src/Xive/StrictCellName.cs
src/Xive/Xocument/CachedXocument.cs
tests/Test.Xive/Cell/CachedCellTests.cs
tests/Test.Xive/Comb/CachedCombTests.cs
tests/Test.Xive/Xocument/CachedXocumentTests.cs

closes #80 
If your cache usage depends on differing between seperators, this PR might break your code.

feat: unify path seperators

---

src/Xive/Hive/FileHive.cs
src/Xive/Hive/MemorizedHive.cs
src/Xive/Hive/RamHive.cs
src/Xive/Hive/TextIndex.cs
src/Xive/IProps.cs
src/Xive/Mnemonic/SimpleMemories.cs
src/Xive/Props/RamProps.cs
src/Xive/Props/SandboxProps.cs
tests/Test.Xive/Hive/FileHiveTests.cs
tests/Test.Xive/Hive/MemorizedHiveTests.cs
tests/Test.Xive/Mnemonic/MemoriesInFilesTests.cs
tests/Test.Xive/Props/RamPropsTests.cs

Xive speedup by storing index and props in text files.
closes #93

feat: store index and props in text files

---

src/Xive/Hive/TextIndex.cs

TextIndex.Has() is not threadsafe.
Threadsafeness is added.
closes #101

fix: threadsafeness

---

src/Xive/Cell/FileCell.cs
src/Xive/Cell/MemorizedCell.cs
src/Xive/Cell/RamCell.cs
src/Xive/Mnemonic/CachedMemories.cs
src/Xive/Mnemonic/CachedMemory.cs
src/Xive/Normalized.cs
src/Xive/Props/SandboxProps.cs
src/Xive/Props/XocumentProps.cs
src/Xive/Xive.csproj
src/Xive/Xocument/FileXocument.cs
src/Xive/Xocument/MemorizedXocument.cs
src/Xive/Xocument/RamXocument.cs
tests/Test.Xive/Test.Xive.csproj

Update the atoms nuget to version 2.0.1

---

src/Xive/Props/RamProps.cs
tests/Test.Xive/Comb/FileCombTests.cs
tests/Test.Xive/Comb/RamCombTests.cs
tests/Test.Xive/Props/RamPropsTests.cs

Bug Refining props with empty values removes the prop

---

src/Xive/Cell/SyncCell.cs
src/Xive/Xocument/SyncXocument.cs
tests/Test.Xive/Cell/SyncCellTests.cs
tests/Test.Xive/Comb/SyncCombTests.cs
tests/Test.Xive/Xocument/SyncXocumentTests.cs

Free cell mutex automatically

---

src/Xive/Mnemonic/Content/CachedContents.cs
tests/Test.Xive/Mnemonic/Content/CachedContentsTests.cs

update ignored files

---

src/Xive/Xocument/SyncXocument.cs
tests/Test.Xive/Comb/SyncCombTests.cs
tests/Test.Xive/Xocument/SyncXocumentTests.cs

fix: syncXocument

---

src/Xive/Hive/TextIndex.cs
tests/Test.Xive/Hive/TextIndexTests.cs

make TextIndex Multithreading safe

---

src/Xive/Props/SandboxProps.cs

use solid in SandboxProps to make it threadsafe

---

src/Xive/Hive/TextIndex.cs
tests/Test.Xive/Hive/TextIndexTests.cs

fix: filter works

---

src/Xive/Hive/TextIndex.cs
tests/Test.Xive/Hive/TextIndexTests.cs

I140 improve index

---

src/Xive/Hive/TextIndex.cs
src/Xive/Mnemonic/Content/FileContents.cs
src/Xive/Props/SandboxProps.cs
tests/Test.Xive/Props/SandboxPropsTests.cs

closes #144 
The reading of the SandboxProps and TextIndex was with Encoding.Default and is now UTF8.

Add utf8 encoding to all string conversions [Breaking Change]

---

appveyor.yml
build.sh
src/Xive/Mnemonic/Content/FileContents.cs
tests/Test.Xive/Hive/FileHiveTests.cs

make removal of empty file hive combs possible

---

src/Xive/Props/SandboxProps.cs

add stringbuilder instead of string variable

---

src/Xive/Mnemonic/CachedMnemonic.cs
src/Xive/Mnemonic/RamMnemonic.cs
src/Xive/Props/CachedProps.cs
tests/Test.Xive/Mnemonic/CachedMnemonicTests.cs
tests/Test.Xive/Props/CachedPropsTests.cs

add cachedProps to cachedMemnonic

---

src/Xive/Xive.csproj

Adds metadata and license information to the NuGet package

---

appveyor.yml
src/Xive/Comb/MemorizedComb.cs
src/Xive/Xive.csproj
tests/Test.Xive/Test.Xive.csproj

Uses old Atoms 2.4.0
Uses Atoms 2.6.0

feat: update packages

---

build.cake

Skip release tasks on ubuntu

---

src/Xive/Mnemonic/Content/FileContents.cs
tests/Test.Xive/Mnemonic/Content/FileContentsTests.cs

Add file path to exception thrown for long paths

---

appveyor.yml
src/Xive/Mnemonic/Cache/BytesCache.cs
src/Xive/Mnemonic/Cache/FkCache.cs
src/Xive/Mnemonic/Cache/IgnoringCache.cs
src/Xive/Mnemonic/Cache/PropsCache.cs
src/Xive/Mnemonic/Cache/XmlCache.cs
src/Xive/Mnemonic/CachedMnemonic.cs
src/Xive/Mnemonic/ICache.cs
tests/Test.Xive/Mnemonic/Cache/PropsCacheTests.cs
tests/Test.Xive/Mnemonic/CachedMnemonicTests.cs

PropsCache is accessable

---

src/Xive/Xive.csproj
tests/Test.Xive/Test.Xive.csproj

add strong name refs

---

src/Xive/Xive.csproj

bump yaapii.xml

---

src/Xive/Hive/MemorizedHive.cs
tests/Test.Xive/AssertException.cs
tests/Test.Xive/Hive/MemorizedHiveTests.cs

closes #186
Empty scopes are now rejected.

reject empty scopes in MemorizedHive
